import styles from './app-footer.module.css';
import { Link, Typography } from '@mui/material';

export default function AppFooter() {
  return (
    <footer className={styles.app_footer}>
      <Typography variant="body1" gutterBottom>
        <Link
          href="https://github.com/LedyBacer/spa-card-testjob"
          variant="body1"
          underline="none"
        >
          spa-card-testjob
        </Link>{' '}
        is maintained by{' '}
        <Link
          href="https://github.com/LedyBacer"
          variant="body1"
          underline="none"
        >
          Nikita Dybov
        </Link>
      </Typography>
      {/*<Typography variant="body2" gutterBottom>*/}
      {/*  This page was generated by{' '}*/}
      {/*  <Link href="https://pages.github.com" variant="body2" underline="none">*/}
      {/*    GitHub Pages*/}
      {/*  </Link>*/}
      {/*</Typography>*/}
    </footer>
  );
}
